[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "bookapi"
version = "0.0.0"
requires-python = ">= 3.8"
dependencies = [
  
]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
strict = true
pythonpath = ["src"]
